### ISSUE TITLE
Consider rebasing "Main" branch as the large files in the history are clogging up cloning the repository

### ISSUE THREAD

**Issue by SimonDarksideJ** [oculus-samples/Unity-AssetStreaming#2]
Looking at the commit history, lots of large files have been moved around the repository, this has caused the git history to be come clogged up and ridiculously oversized.

It took an extra ordinate amount of time to clone the project and longer to filter to the main branch.

Please consider rebasing to clear-out the history and move the "non-addressables" branch to a separate repo (linked) to save developers time cloning the project to investigate it.

P.S. 
Great work on the project, looks awesome.

**Comment by AlexThiv** [comment]
Hi,

When you mention extra ordinate amount of time to clone and filter, do you have more specifics time values? On our side it takes about 6-8minutes, considering that it's a large repo due to the assets it seems reasonable. Do you have to wait way longer than that?

As for the history, it's 6 commits (as of this moment) and the large files haven't moved since the initial commit. If you can provide more details, we will be happy to look into it more specifically.

We are glad you enjoy the project and we want to make sure you have the best experience testing it out.

**Comment by SimonDarksideJ** [comment]
Granted yes, the project is large with some large assets, but the git size is doubled due to the retention of the "pre-addressables" branch as well.
I'd recommend splitting out the "pre-addressables" branch in to a separate repo, then rebasing this branch based on its latest commit.  This should considerably cut down the size of the repo and speed up access to it.
(or drop/recreate the repo, links should be preserved, with just the current state)

**Comment by AlexThiv** [comment]
Hi @SimonDarksideJ,

Thanks for the additional information. After looking more in depth about what you are reporting. What you are seeing is due to the use of git lfs, for the large file storage. In short, the lfs files are stored in the .git/lfs directory and they are also placed in the working directory where they are reference, which in the end does cause the whole clone directory to be 2x the lfs files plus the other files that aren't tracked by LFS. This also means that when any changes is done to a file tracked by lfs, only the referred lfs file will be downloaded instead of each iteration of a same file.

The non-addressables branch references the same lfs files and therefore doesn't add to the size. I want to note that most files from that branch have not been modified and are referencing the same version of the file.

You can find more information about git lfs [here](https://git-lfs.github.com/).

When cloning the repository clean, we see the directory with a size of 27.8 GB (which is what we expect from our above explanation), do you have a different experience?

We hope that this gives you a bit more clarity on the state you are seeing.

**Comment by SimonDarksideJ** [comment]
Fair enough, best to update the Readme to set consumers expectations for what they will be seeing/getting
